layout_spectrum: 0.1702128
color:
  saturation: 1
  lightness: 1
  brandStrength: 1
  brandColors:
    - '#B47877'
    - '#7F3930'
    - '#CF4230'
    - '#6D160D'
    - '#F2B6B3'
  rhythmicContrast: 1
typography_spectrum: 0.4723404
name: Cassis Staudt
